[Icon Theme]
Name=Mint XP Experience Icons
Comment=Original perspective desktop artwork
Inherits=Mint-Y,Adwaita,hicolor
Directories=16/actions,16/apps,16/categories,16/devices,16/mimetypes,16/places,24/actions,24/apps,24/categories,24/devices,24/mimetypes,24/places,32/actions,32/apps,32/categories,32/devices,32/mimetypes,32/places,48/actions,48/apps,48/categories,48/devices,48/mimetypes,48/places,scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/mimetypes,scalable/places

[16/actions]
Size=16
Type=Fixed
Context=Actions

[16/apps]
Size=16
Type=Fixed
Context=Applications

[16/categories]
Size=16
Type=Fixed
Context=Categories

[16/devices]
Size=16
Type=Fixed
Context=Devices

[16/mimetypes]
Size=16
Type=Fixed
Context=MimeTypes

[16/places]
Size=16
Type=Fixed
Context=Places

[24/actions]
Size=24
Type=Fixed
Context=Actions

[24/apps]
Size=24
Type=Fixed
Context=Applications

[24/categories]
Size=24
Type=Fixed
Context=Categories

[24/devices]
Size=24
Type=Fixed
Context=Devices

[24/mimetypes]
Size=24
Type=Fixed
Context=MimeTypes

[24/places]
Size=24
Type=Fixed
Context=Places

[32/actions]
Size=32
Type=Fixed
Context=Actions

[32/apps]
Size=32
Type=Fixed
Context=Applications

[32/categories]
Size=32
Type=Fixed
Context=Categories

[32/devices]
Size=32
Type=Fixed
Context=Devices

[32/mimetypes]
Size=32
Type=Fixed
Context=MimeTypes

[32/places]
Size=32
Type=Fixed
Context=Places

[48/actions]
Size=48
Type=Fixed
Context=Actions

[48/apps]
Size=48
Type=Fixed
Context=Applications

[48/categories]
Size=48
Type=Fixed
Context=Categories

[48/devices]
Size=48
Type=Fixed
Context=Devices

[48/mimetypes]
Size=48
Type=Fixed
Context=MimeTypes

[48/places]
Size=48
Type=Fixed
Context=Places

[scalable/actions]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=Actions

[scalable/apps]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=Applications

[scalable/categories]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=Categories

[scalable/devices]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=Devices

[scalable/mimetypes]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=MimeTypes

[scalable/places]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
Context=Places
